(ignore-errors (org-babel-load-file (buffer-file-name)))

(require 'mandoku)
(require 'mandoku-remote)
(require 'org-mandoku)
(require 'mandoku-dict)
(setq org-return-follows-link t)
(setq mandoku-do-remote t)
(setq mandoku-string-limit 10)
(setq mandoku-index-display-limit 2000)
(setq mandoku-local-init-file (concat mandoku-meta-dir "settings.org"))
(ignore-errors 
 (load "mandoku-dict" t)
 (global-set-key [f5] 'mandoku-dict-mlookup))
(global-set-key [f6] 'mandoku-search-text)
(global-set-key [f7] 'mandoku-search-titles)
(setq org-support-shift-select 'always)

(let ((uval (quote (("Key" "Value" "備考") ("Server" "gl.kanripo.org" "") ("Email" "" "メール") ("Account" "" "アカウント名") ("Token" "" "トークン")))))
(mandoku-set-settings uval)
(car (cdr (assoc "Email" uval ))) 
)

(let ((uval (quote (("ZB" "http://www.kanripo.org/zb")))))
(mandoku-set-repos uval)
)

(setq mandoku-text-dir (expand-file-name (concat mandoku-base-dir "text/")))
(setq mandoku-meta-dir (expand-file-name  (concat mandoku-base-dir "meta/")))
(setq mandoku-temp-dir (expand-file-name  (concat mandoku-base-dir "temp/")))
(setq mandoku-sys-dir (expand-file-name  (concat mandoku-base-dir "system/")))
(setq mandoku-dict-url "http://www.kanripo.org/zb")
(setq mandoku-catalogs-alist nil)
(dolist (dir (directory-files mandoku-meta-dir nil "^[^.,].*"))
  (when (file-directory-p (concat mandoku-meta-dir dir))
    (dolist (file (directory-files (concat mandoku-meta-dir dir) nil ".txt" ))
      (add-to-list 'mandoku-catalogs-alist 
   (cons (file-name-sans-extension file) (concat mandoku-meta-dir dir "/" file))))))
(mandoku-read-titletables) 
(setq mandoku-catalog (concat mandoku-meta-dir "mandoku-catalog.txt"))
(setq mandoku-initialized t)
(message "Loading of local setup for Mandoku finished")
(find-file mandoku-catalog)
