#+TITLE: =マンドク= のテキスト形式
#+OPTIONS: toc:nil ^:nil

=マンドク= に使用されているテキスト形式は三つの部分によって構成されている：
 - 基本はEmacsのorg-modeのファイル形式
 - テキストをファイルに纏める時の幾つかの慣例
 - ファイル内の特定な書き方

* テキスト形式はEmacsのorg-modeに基づいて実装された

  テキスト・エディターEmacsには「モード」という概念がある。様ざまなテキ
  ストの種類、例えば各種のプログラミング言語などは「モード」によってそ
  の種類のテキストに特化したテキスト編集を支援するが可能になり、それに
  よってより簡単、早い、効率よい編集作業が出来る。Org-modeは対象とする
  形式はいわゆる「プレーン･テキスト」、つまり普通の文書のテキストをより
  快適に編集出来るようのためのモードだ。

  これを可能にするため、org-modeで扱う「プレーン･テキスト」は以下の様な
  幾つかの特徴がある(ここで紹介するのは一部であり、[[http://orgmode.org/ja/features.html][詳細な紹介はこちら]])：
  
  - テキストに「見出し」の概念があり、各レベルの見出しは行の右に"* "を
    入れるで作成する。星の数はレベルを示唆する。星マークは必ず半角モー
    ド(英数)で入力し、最後に(つまり実際の見出しの文字列の前)半角のスペー
    スが必要。
   : * Outline level one レベル１の見出し
   : ** Outline level two レベル２の見出し
   : *** Outline level three レベル３の見出し
  - 見出しの次の行に「property drawer」(属性抽斗)というものをつけれる、
    ここにはこの見出しに関連する機会可読な情報を入れる(例えばここへの
    リンクに使う'CUSTOM_ID')：
   : * 序論
   :  :PROPERTIES:
   :  :CUSTOM_ID: intro
   :  :END:

  - 見出しに「tag」(タグ)も付けれる、それはこの見出しに関連する分類、整
    理のための情報などに使える；タグは右詰めに、前後に半角のコロンで入
    力する。
   : * Outline level one レベル１の見出し	      :重要:

  - 段落は空き行で記述する。

  - テキストに引用文('QUOTE')或は詩の形('VERSE')などがあるとそれは特殊な
    セクションとして記述できる：
: 即於佛前以偈頌曰。
: #+BEGIN_VERSE
: 目淨脩廣如青蓮
: 心淨已度諸禪定
: 久積淨業稱無量
: 導眾以寂故稽首
: #+END_VERSE
    
  - '#'半角のハッシュ・マークで始まる行は特別に処理される：
    - "#+"はorg-mode様な特別な用語に使う、例えば =#+TITLE= 'タイトル',
      =#+AUTHOR= '著者' or =#+DATE= '日付'など。
    - "# "(半角スペース)は一般のコメントを導入する、このコメントはテキ
      ストの本文の内容とは別になる。
  - 他ファイルへのリンクは次のように作られる：
    =[[目的.txt][目的.txtへのリンク] ]= 


* =マンドク= に特有の慣例
** テキスト、バーション、エディションなど
   =マンドク= では各テキストに特有なID番号(例: =T14n0475=)が設定され、
   それを以ってテキスト・コレクションの中で、ある一つのテキストをはっき
   り特定できる。　このテキストIDは大体テキストが保存されたフォルダー名
   にも使われる、このフォルダーないにはこのテキストに関するすべてのファ
   イルが収集される。多くのテキストは巻毎に分割されて、各ファイルは順序
   に番号がつけられている。 目次用のファイルも作られる。
#+CAPTION: 維摩経の序、三巻と目次
#+NAME: ex1
#+BEGIN_EXAMPLE
T14n0475_000.txt
T14n0475_001.txt
T14n0475_002.txt
T14n0475_003.txt
T14n0475.org
#+END_EXAMPLE

   各ファイルのソース(原本)はWITNESS('証拠')として、デジタル・テキスト
   全体の定本("BASEEDITION")はそれそれ各ファイルに記録される。ページ番
   号と改行は定本の通りにきろくされて、各バーションの共通指南となる。

   複数なバーションのテキストは記録可能だ、それによってるテキストの必要
   な情報をすべて管理することは可能になる。 =マンドク= に於いては全ての
   バーション('証拠')は版管理システムの'branch'(枝)として保存される。

   各バーションに横断的に使える位置情報のために定本のページ番号と改行記
   号は各バーションに書き込む。違う版式のバーションはそれに加えてそのバー
   ションの情報も記録するは出来る。
   
** =マンドク= ファイル内の特定な書き方

   
*** 定本と'証拠'本
    =マンドク=では、定本と証拠本等についての情報はファイルの冒頭に機械可読な形式で付けれる：

: #+PROPERTY: BASEEDITION T
: #+PROPERTY: ID T14n0475
: #+PROPERTY: WITNESS 【CBETA】
: #+PROPERTY: JUAN 1

    この例では定本は'T'として記録されて、証拠本(つまるこのファイルで記
    録されていいるバーション)は'【CBETA】'として挙げられている。それに
    加えて、テクストのIDと巻数も記録されている。

*** ページ番号

    ページ番号は次の形で記録されている：
: <pb:T_T14n0475_0537a>

    ページ番号記述は'_'で三つの部分に分けて、'<pb: .. >'囲みされている：
    - 'T' : 定本
    - 'T14n0475' : テキストID
    - '0537a' : ページ番号 （'a'は木版の表、或はパージの上半部分を指し
      ているが、 =マンドク= に於いては現時点ページ番号の末に半角ローマ
      字文字が必要）。
*** 改行記号
    テキストないの位置情報として =マンドク= は定本に於ける改行位置を記
    録する。ページ番号を合わせて、それで全体のテキスト内の位置を正確に
    分かる。改行記号として'¶'(U+00B6')を使用する：
#+BEGIN_SRC 
復有萬梵天王尸棄等，從餘四天下，來詣¶
佛所，而聽法；復有萬二千天帝，亦從餘四¶
天下，來在會坐；并餘大威力諸天、龍神、夜¶
叉、乾闥婆、阿脩羅、迦樓羅、緊那羅、摩睺羅¶
伽等，悉來會坐。
#+END_SRC

    これでテキストを「一行一句」の形式に変えても位置情報が代わらない：

#+BEGIN_SRC 
復有萬梵天王尸棄等，
從餘四天下，
來詣¶佛所，
而聽法；
復有萬二千天帝，
亦從餘四¶天下，
來在會坐；
并餘大威力諸天、
龍神、
夜¶叉、
乾闥婆、
阿脩羅、
迦樓羅、
緊那羅、
摩睺羅¶伽、
等悉來會坐。
#+END_SRC

*** 割注
    原文にある割注は"("と")"の丸括弧に囲む。

*** 注釈、翻訳などの追加情報

    慣例によって、 =マンドク= では行の始めから第一TAB記号(U+0009)まで原
    文のテキストとする。タブ記号の右側にあるテキストは原文として見ださ
    い、位置情報にも影響しない。以下は先の例に英訳を付けている(英訳はジョ
    ン R.マクレーが仏教伝道協会で出版された維摩経訳より)：

#+BEGIN_SRC 
復有萬梵天王尸棄等。　　　　　　5. There were also ten thousand Brahmā heavenly kings, Śikhin and others, 
從餘四天下來詣¶佛所而聽法。　　who descended from the other worlds of four continents to proceed to where the Buddha was in order to hear the Dharma. 
復有萬二千天帝。　　　　　　　　There were also twelve thousand heavenly emperors (i.e., Indras), 
亦從餘四¶天下來在會坐。　　　　who also came from the other worlds of four continents to sit in this assembly, 
并餘大威力諸天．　　　　　　　　and the other awesomely powerful gods (devas), 
龍神．　　　　　　　　　　　　　dragons (nāgas), 
夜¶叉．　　　　　　　　　　　　yakṣas, 
乾闥婆．　　　　　　　　　　　　gandharvas, 
阿脩羅．　　　　　　　　　　　　asuras, 
:zhu:
阿脩羅 [a1xiu1luo1] skt Asura, deities of the lowest rank.
:END:
迦樓羅．　　　　　　　　　　　　garuḍas, 
緊那羅．　　　　　　　　　　　　kiṃnaras, 
摩睺羅¶伽．　　　　　　　　　　and mahoragas, 
等悉來會坐。　　　　　　　　　who all came to sit in the assembly. 
#+END_SRC

    さらに注釈の為に =マンドク= では'zhu'という'抽斗'が定義されている、
    ここでは前の行にある語彙や文字などについての注釈、読書ノートなど書
    き込まれる。この注釈も原文のテキストと見出さない。


