#+TITLE: The mandoku text format


* Based on org-mode

  Emacs org-mode (see [[http://orgmode.org/][Org-Mode: Your Life in Plain Text]]) is basically
  plain text with some outlining, formatting and hyperlinking
  conventions.  This makes it a lightweight text format that covers
  some middle ground between absolutely complete plain text (if such a
  thing exists) and complex markup languages like XML.  Since it even
  supports footnotes and is easily converted to HTML, Latex and
  OpenOffice format, it is useable even for research articles.

* Mandoku extensions to org-mode
  
  Based on earlier work on a text model for premodern Chinese texts,
  requirements for representing such texts where established.  While
  most of these requirements concern the processing, it was also
  established that a convenient framework for adressing characters in
  the text is needed.  This is done by using the page as a fundamental
  unit and text lines on that page as secondary unit.  Within lines,
  characters are then simply indexed.  Mandoku thus requires pages and
  lines marked in the text to function properly.
   

** page identification

   A page identification is given at the start of a page with the
   following template: 
#+begin_example
<pb:[edition identification]_[text identification]_[page identification]>
#+end_example
   for example:
#+begin_example
<pb:T_T51n2076_0281c>
#+end_example
   would be 
   * edition identifier:  T
   * text identifier: T51n2076
   * page identifier: 281c
     
   These three pieces are then assembled according to the template
   shown above.  All of these can be chosen as needed. The edition
   identifies the printed text, which supposedly is the source of this
   digital edition.  The text identifier should identify the text
   uniquely in a collection, while the page identifier should be
   unique within that text.  For text digitized from woodblock prints,
   it is therefore necessary to work the section, booklet or whatever
   into this identifier to disambiguate the page number.

   If there are multiple editions of the same text, the <pb: template
   always has the page identifier for the edition associated with this
   specific version of the digital text.  In some cases, an additional
   identifier for a reference edition has to be introduced, in such
   cases the template would be to simply change 'pb' to 'md' in the
   page identification template, thus resulting in something like
   this:
:<md:T_T51n2076_0281c>


     
** 

