#+TITLE: Installing and using the Mandoku preview version
#+DATE: 2013-09-26
#+OPTIONS: toc:nil ^:nil

* Installing the preview version of Mandoku

  As of late September 2013, a preview version of =Mandoku= is
  available.  This implements a not yet complete new version of
  =Mandoku=.  This preview version can be installed by either
  downloading a package for Mac or for Windows, or by downloading the
  Mandoku library and manually installing it.  The latter is only
  recommended for experienced Emacs users and does not work (well?) on
  Windows.

  Requirements:
  - On all platforms, =git= is required for the installation process
    and software updates.
  - A working network connection

** Installing a package for Windows

   The package for Windows has been tested on Windows 8.  It might
   work on earlier versions, but there might also be problems.  The
   Emacs application included in the =Mandoku= package below is the
   one from [[http://ftp.gnu.org/gnu/emacs/windows/emacs-24.3-bin-i386.zip][the Gnu software archive]] (version 24.3 of March 2013); the
   only modification is that a startup file has been placed in the
   =site-lisp= directory.
   
   1. The =Mandoku= preview package includes a version of the =git=
      program, which is used to download and update necessary
      files. If you want to use =git= outside of =Mandoku=, it is
      recommended to download and install the =git= software from the
      [[http://code.google.com/p/msysgit/downloads/list?q=full+installer+official+git][msysgit software repository]]; the current version is
      [[http://code.google.com/p/msysgit/downloads/list?q=full+installer+official+git][Git-1.8.4-preview]].
   2. Download the =Mandoku= installation package from [[http://www.mandoku.org/]
   3. Doubleclick on the package and move the folder =krp=, which is
      found inside the package to a destination on a root directory of
      your computer.  It is highly recommended to use the system drive
      =C:= as a destination.
   4. Within the folder =krp=, find the file "Emacs" and move it to
      the Desktop (this will work only if you put the folder on drive
      =C:=.  Alternatively, you can locate the file =(Your drive
      letter):\krp\bin\emacs-24.3\bin\runemacs.exe=, right-click
      on this file and create a shortcut on a destination of your
      liking.  On Windows 8 you can also start the application by
      clicking on the file and then "pin" it to the taskbar, where you
      will easily find it the next time.

      

** Installing a package for Macintosh

   The package for Macintosh has been tested on OS X 10.8 (Mountain
   Lion) and OS X 10.6 (Snow Leopard).  It might also work on other
   versions.

   The Emacs binary available in the package below has been modified
   by applying a patch from Yamamoto Mitsuharu and by placing a
   startup file in the =site-lisp= directory.

   1. On OS X 10.6 it is necessary to first install the =git=
      program. Please download the installer from the
      [[http://code.google.com/p/git-osx-installer/][git-osx-installer]] software archive: the current version is [[http://code.google.com/p/git-osx-installer/downloads/detail?name=git-1.8.3.2-intel-universal-snow-leopard.dmg&can=3&q=&sort=-uploaded][Git
      1.8.3.2]]. Doubleclick on the downloaded file and again on the
      file =name=git-1.8.3.2-intel-universal-snow-leopard.dmg= to
      mount it, now click on the file
      =name=git-1.8.3.2-intel-universal-snow-leopard.pkg= and follow
      the on-screen instructions to install the software.  This is not
      necessary on OS X 10.8.
   2. Download and open the =Mandoku= preview package [[mandoku-preview-2013-09-26.dmg]].
   3. There are two items in the volume:
      - =Emacs=
      - =krp=
   4. Drag =Emacs= into the Applications folder.  If there is already
      an item called =Emacs=, it is recommended to replace this
      item. If you use this frequently, you can place =Emacs= in the
      dock for convenient access.
   5. Drag =krp= to your home directory. Alternatively, you can also
      drag this to the =Shared= folder so that it can be used by other
      users of the computer.



** Installing =Mandoku= into existing Emacs installations

   =Mandoku= consists of a package with Emacs-lisp (and some other)
   code, and of metadata necessary for the operation, this makes the
   installation more complicated than is usually the case for Emacs
   add-on packages.

   The easiest way to include it into existing installations (on
   Windows or Macintosh) is to use the above mentioned packages and
   then make sure that =mandoku-default.el= (in the =mandoku/lisp=
   directory) is loaded; this should take care of the initialization
   by setting some variables and then loading =mandoku-local-init=
   from your Emacs init directory; the latter file should have been
   created during installation.
   
   In addition to this, there are two ways to accomplish the install manually:
   1. Using the file =mandoku-install= by evaluating the following
      elisp expression:
#+BEGIN_SRC elisp
(setq mandoku-base-dir "~/krp")
(with-temp-buffer (url-insert-file-contents 
       "https://raw.github.com/cwittern/mandoku/master/lisp/mandoku-install.el")
  (eval-region (point-min) (point-max)))
  (mandoku-install mandoku-base-dir)
  (add-to-list 'load-path user-emacs-directory)
  (mandoku-setup-local-init-file)
  (load "mandoku-local-init")
#+END_SRC
      This will install the program code and necessary files under the
      base directory =krp= in your home directory. It will also clone
      the metadata repository and compile the necessary files, this
      might take at least 10 minutes to finish.



   2. Alternatively, you might want to follow the steps in
      =mandoku-install= manually to understand what exactly is
      installed to your computer.  

      
   So far, the preview package has not been tested under systems other
   than Windows and Macintosh, but I would be very interested to know
   the results of such an experiment.





* Using the preview version

  At the moment, only a small fraction of the planned functionality
  has been realized.

  After starting Emacs with the =Mandoku= preview package installed,
  Emacs will display the file =mandoku-catalog.txt=, which is a list
  of catalog files available locally.  The catalog files themselves
  can be browsed by clicking on the filename links.  

  Another purpose of displaying the catalog list is the fact that this
  allows the menu for =Mandoku= to appear.  This menu is only
  available in =Mandoku= files (Emacs can display a large number of
  different file types, most of them are accompanied by corresponding
  menu entries).  =Mandoku= files are recognizable by the string
  "mandoku-view" in the lower part of the part of the screen that
  displays this file, in addition to that, they also show the title of
  the text and some more information about the text and the current
  location within the text.

  The =Mandoku= menu has the following top level entries:
  - Markers
  - Browse
  - Search
  - Versions
  - Maintenance

  Of these, we will first look at the "Search" menu, which has the following entries:
  - Texts       <f6>
  - Titles      <f7>
  - Dictionary  <f5>

  There are three different search actions, that is, within the texts,
  within the titles of the texts and within the dictionaries.  We will
  look at these in turns, but before that I want to mention that the
  mysterious "<f6>", "<f7>" and "<f5>" that appear on the menu are the
  keys that can be used to access this same functionality; usually it
  is much faster to use the keyboard.
  
** Text search
   At the moment, the text search function conducts a full-text search
   in the index, that has been generated for this purpose and displays
   the results as a keywoard in context (KWIC) list of matches. 

   When activating the menu or pressing the key F6, =Mandoku= will
   look at the characters immediately following the current position
   in the text displayed and offer them as default search key at the
   bottom of the =Emacs= application window. (This is called the
   minibuffer and serves a similar purpose dialog boxes have in other
   applications, that is, they are used for interaction with the user)

   =Mandoku= suggests six characters, but in most cases fewer
   characters are sufficient as search word.  However, at the moment
   =Mandoku= will refuse to display more than 2000 hits, so a search
   for just one or two characters will in many cases go over the
   limit, which then only displays a breakdown of the number of hits
   across the different parts of the collection, so it is recommended
   to use at least 3 characters for searching. If necessary, the
   suggested characters can of course be completely deleted and the
   desired search term given.

   If there are less than 2000 matches, a list of these matches is
   displayed. The display is in a very simple table, that gives the
   location of the match (usually the /juan/ number, page and line), a
   few characters left and right of the match and the text, where this
   match is found.  The text identification consists of the text
   number and the title of the text.  Both the location and the text
   title are active links.  Clicking on the location

