#+TITLE: Installing and using the Mandoku preview version
#+DATE: 2013-09-26
#+OPTIONS: toc:nil ^:nil

* Installing the preview version of Mandoku

  As of late September 2013, a preview version of =Mandoku= is
  available.  This implements a not yet complete new version of
  =Mandoku=.  This preview version can be installed by either
  downloading a package for Mac or for Windows, or by downloading the
  Mandoku library and manually installing it.  The latter is only
  recommended for experienced Emacs users and does not work (well?) on
  Windows.

  Requirements:
  - On all platforms, =git= is required for the installation process
    and software updates.
  - A working network connection

** Installing a package for Windows

   The package for Windows has been tested on Windows 8.  It might
   work on earlier versions, but there might also be problems.  The
   Emacs application included in the =Mandoku= package below is the
   one from [[http://ftp.gnu.org/gnu/emacs/windows/emacs-24.3-bin-i386.zip][the Gnu software archive]] (version 24.3 of March 2013); the
   only modification is that a startup file has been placed in the
   =site-lisp= directory.
   
   1. The =Mandoku= preview package includes a version of the =git=
      program, which is used to download and update necessary
      files. If you want to use =git= outside of =Mandoku=, it is
      recommended to download and install the =git= software from the
      [[http://code.google.com/p/msysgit/downloads/list?q=full+installer+official+git][msysgit software repository]]; the current version is
      [[http://code.google.com/p/msysgit/downloads/list?q=full+installer+official+git][Git-1.8.4-preview]].
   2. Download the =Mandoku= installation package from [[http://www.mandoku.org/]
   3. Doubleclick on the package and move the folder =krp=, which is
      found inside the package to a destination on a root directory of
      your computer.  It is highly recommended to use the system drive
      =C:= as a destination.
   4. Within the folder =krp=, find the file "Emacs" and move it to
      the Desktop (this will work only if you put the folder on drive
      =C:=.  Alternatively, you can locate the file =(Your drive
      letter):\krp\bin\emacs-24.3\bin\runemacs.exe=, right-click
      on this file and create a shortcut on a destination of your
      liking.  On Windows 8 you can also start the application by
      clicking on the file and then "pin" it to the taskbar, where you
      will easily find it the next time.

      

** Installing a package for Macintosh

   The package for Macintosh has been tested on OS X 10.8 (Mountain
   Lion) and OS X 10.6 (Snow Leopard).  It might also work on other
   versions.

   The Emacs binary available in the package below has been modified
   by applying a patch from Yamamoto Mitsuharu and by placing a
   startup file in the =site-lisp= directory.

   1. On OS X 10.6 it is necessary to first install the =git=
      program. Please download the installer from the
      [[http://code.google.com/p/git-osx-installer/][git-osx-installer]] software archive: the current version is [[http://code.google.com/p/git-osx-installer/downloads/detail?name=git-1.8.3.2-intel-universal-snow-leopard.dmg&can=3&q=&sort=-uploaded][Git
      1.8.3.2]]. Doubleclick on the downloaded file and again on the
      file =name=git-1.8.3.2-intel-universal-snow-leopard.dmg= to
      mount it, now click on the file
      =name=git-1.8.3.2-intel-universal-snow-leopard.pkg= and follow
      the on-screen instructions to install the software.  This is not
      necessary on OS X 10.8.
   2. Download and open the =Mandoku= preview package [[mandoku-preview-2013-09-26.dmg]].
   3. There are two items in the volume:
      - =Emacs=
      - =krp=
   4. Drag =Emacs= into the Applications folder.  If there is already
      an item called =Emacs=, it is recommended to replace this
      item. If you use this frequently, you can place =Emacs= in the
      dock for convenient access.
   5. Drag =krp= to your home directory. Alternatively, you can also
      drag this to the =Shared= folder so that it can be used by other
      users of the computer.



** Installing =Mandoku= into existing Emacs installations

   =Mandoku= consists of a package with Emacs-lisp (and some other)
   code, and of metadata necessary for the operation, this makes the
   installation more complicated than is usually the case for Emacs
   add-on packages.

   The easiest way to include it into existing installations (on
   Windows or Macintosh) is to use the above mentioned packages and
   then make sure that =mandoku-default.el= (in the =mandoku/lisp=
   directory) is loaded; this should take care of the initialization
   by setting some variables and then loading =mandoku-local-init=
   from your Emacs init directory; the latter file should have been
   created during installation.
   
   In addition to this, there are two ways to accomplish the install manually:
   1. Using the file =mandoku-install= by evaluating the following
      elisp expression:
#+BEGIN_SRC elisp
(setq mandoku-base-dir "~/krp")
(with-temp-buffer (url-insert-file-contents 
       "https://raw.github.com/cwittern/mandoku/master/lisp/mandoku-install.el")
  (eval-region (point-min) (point-max)))
  (mandoku-install mandoku-base-dir)
  (add-to-list 'load-path user-emacs-directory)
  (mandoku-setup-local-init-file)
  (load "mandoku-local-init")
#+END_SRC
      This will install the program code and necessary files under the
      base directory =krp= in your home directory. It will also clone
      the metadata repository and compile the necessary files, this
      might take at least 10 minutes to finish.



   2. Alternatively, you might want to follow the steps in
      =mandoku-install= manually to understand what exactly is
      installed to your computer.  

      
   So far, the preview package has not been tested under systems other
   than Windows and Macintosh, but I would be very interested to know
   the results of such an experiment.





* Using the preview version

  At the moment, only a small fraction of the planned functionality
  has been realized.

  After starting Emacs with the =Mandoku= preview package installed,
  Emacs will display the file =mandoku-catalog.txt=, which is a list
  of catalog files available locally.  The catalog files themselves
  can be browsed by clicking on the filename links.  

  Another purpose of displaying the catalog list is the fact that this
  allows the menu for =Mandoku= to appear.  This menu is only
  available in =Mandoku= files (Emacs can display a large number of
  different file types, most of them are accompanied by corresponding
  menu entries).  =Mandoku= files are recognizable by the string
  "mandoku-view" in the lower part of the part of the screen that
  displays this file, in addition to that, they also show the title of
  the text and some more information about the text and the current
  location within the text.

  The =Mandoku= menu has the following top level entries:
  - Markers
  - Browse
  - Search
  - Versions
  - Maintenance

  Of these, we will first look at the "Search" menu, which has the following entries:
  - Texts       <f6>
  - Titles      <f7>
  - Dictionary  <f5>

  There are three different search actions, that is, within the texts,
  within the titles of the texts and within the dictionaries.  We will
  look at these in turns, but before that I want to mention that the
  mysterious "<f6>", "<f7>" and "<f5>" that appear on the menu are the
  keys that can be used to access this same functionality; usually it
  is much faster to use the keyboard.
  
** Text search
   At the moment, the text search function conducts a full-text search
   in the index, that has been generated for this purpose and displays
   the results as a keywoard in context (KWIC) list of matches. 

   When activating the menu or pressing the key F6, =Mandoku= will
   look at the characters immediately following the current position
   in the text displayed and offer them as default search key at the
   bottom of the =Emacs= application window. (This is called the
   minibuffer and serves a similar purpose dialog boxes have in other
   applications, that is, they are used for interaction with the user)

   =Mandoku= suggests six characters, but in most cases fewer
   characters are sufficient as search word.  However, at the moment
   =Mandoku= will refuse to display more than 2000 hits, so a search
   for just one or two characters will in many cases go over the
   limit, which then only displays a breakdown of the number of hits
   across the different parts of the collection, so it is recommended
   to use at least 3 characters for searching. If necessary, the
   suggested characters can of course be completely deleted and the
   desired search term given.

   If there are less than 2000 matches, a list of these matches is
   displayed. The display is in a very simple table, that gives the
   location of the match (usually the /juan/ number, page and line), a
   few characters left and right of the match and the text, where this
   match is found.  The text identification consists of the text
   number and the title of the text.  Both the location and the text
   title are active links.  Clicking on the location will open the
   text at the place where this passage is found and usually highlight
   the search term (this will not work always,
   unfortunately). Clicking on the text title will open the
   corresponding catalog file and display the entry for this text.

   The search result is a text file, similar to the format of the
   texts themselves.  It can be copied, saved and reopened or edited
   as needed. The order of the displayed items is according to the
   text following the term, which should put related passages in the
   vicinity of each other.  It is also possible to change the order of
   the displayed items, but that is an advanced topic that will be
   dicussed later.

** Title search
   To locate a text and start reading it, title search is most
   convenient. Title search is activated with F7 or from the menu as
   shown.  Again it will display a prompt at the bottom of the screen
   and ask for the title to search for.  

   The result of the search will be displayed in a separate buffer in
   a table with several columns, displaying the "Bu" (Section), text
   number, text title, dynasty and author (or otherwise responsible
   person) for the text.  This information is taken from the catalog
   file, but pre-indexed for faster access.  Changes in the catalog
   file will require a re-indexing. 

   As usual, the cursor can be moved around to go to the desired row
   in the file. The original order is by title, but clicking on the
   top row, where the column names are displayed, will change the sort
   order according to the column, this allows for example texts from
   the same dynasty or the same author to be displayed closely
   together. On the row with the desired text, pressing "t" (text)
   will display the text, while pressing "i" (information) or "c"
   (catalog) will go to the catalog entry.


** Dictionary search

   Dictionary search is initiated by pressing F5. If some text has
   been selected, this selected text will be the search term.
   Otherwise, the line of text that is currently displayed will be the
   searched for.  For every string of one or more characters that has
   an entry in at least one of the dictionaries, an item is generated
   in the dictionary display.  In the dictionary display buffer, the
   first line will display the text location, if one had been
   identified, the following lines, beginning with two "**" characters
   will contain the dictionary information.  Moving the cursor (or
   "point") to the beginning of this line and then pressing the "tab"
   key will open the display and reveal a list of the dictionaries
   that contain this term. Pressing the "tab" key again will open all
   dictionary entries at the same time. This might be a bit confusing,
   in which case one can move the point to the beginning of the
   desired line and press "tab" again. Some dictionaries have the full
   text, others have only a reference to the page (and volume) where
   the entry is found.  These are listed under the last entry "其他詞典".
   
