#+TITLE: Installing Mandoku
#+DATE: 2013-09-26
#+OPTIONS: toc:nil ^:nil

* Preview version of Mandoku

  As of late September 2013, a preview version of =Mandoku= is
  available.  This implements a not yet complete new version of
  =Mandoku=.  This preview version can be installed by either
  downloading a package for Mac or for Windows, or by downloading the
  Mandoku library and manually installing it.  The latter is only
  recommended for experienced Emacs users and does not work (well?) on
  Windows.

  Requirements:
  - On all platforms, =git= is required for the installation process
    and software updates.
  - A working network connection

** Installing a package for Windows
   
   1. Before installing =Mandoku=, please download and install the =git= software from the 
      [[http://code.google.com/p/msysgit/downloads/list?q=full+installer+official+git][msysgit software repository]]; the current version is [[http://code.google.com/p/msysgit/downloads/list?q=full+installer+official+git][Git-1.8.4-preview]].
   2. Download the =Mandoku= installation package from [[http://www.mandoku.org/]
   3. Doubleclick on the package and move the folder =krp=, which is
      found inside the package to a destination on a root directory of
      your computer.  It is highly recommended to use the system drive
      =C:= as a destination.
   4. Within the folder =krp=, find the file "Emacs" and move it to
      the Desktop (this will work only if you put the folder on drive
      =C:=.  Alternatively, you can locate the file =(Your drive
      letter):\krp\bin\emacs-24.3\bin\emacsclientw.exe=, right-click
      on this file and create a shortcut on a destination of your
      liking.
      


